"""bookclub_users model update

Revision ID: 055c8ecc6258
Revises: d58a85e25a1a
Create Date: 2025-02-11 12:02:03.833302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055c8ecc6258'
down_revision = 'd58a85e25a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookclub_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('invited_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('responded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookclub_users', schema=None) as batch_op:
        batch_op.drop_column('responded_at')
        batch_op.drop_column('invited_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
