"""removing chatlogs

Revision ID: 222851036b5d
Revises: ffd4d658ebb2
Create Date: 2025-02-26 21:25:07.678283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '222851036b5d'
down_revision = 'ffd4d658ebb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatlogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatlogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('bookclub_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bookclub_id'], ['bookclubs.id'], name='fk_chatlogs_bookclub_id_bookclubs'),
    sa.PrimaryKeyConstraint('id', name='chatlogs_pkey')
    )
    # ### end Alembic commands ###
