"""book model update

Revision ID: 538fbeb021e6
Revises: 03ba9a5ee0cf
Create Date: 2025-02-16 11:49:26.554815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538fbeb021e6'
down_revision = '03ba9a5ee0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('spine_image')
        batch_op.drop_column('release_date')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('spine_image', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
