"""create all tables

Revision ID: 711d5b6b490d
Revises: 0e758ce5ef9b
Create Date: 2025-02-17 20:44:52.067773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711d5b6b490d'
down_revision = '0e758ce5ef9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookclubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('accolade', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('streak', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bookclub_users',
    sa.Column('bookclub_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bookclub_id'], ['bookclubs.id'], name=op.f('fk_bookclub_users_bookclub_id_bookclubs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookclub_users_user_id_users')),
    sa.PrimaryKeyConstraint('bookclub_id', 'user_id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_books_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookshelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookshelves_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('bookclub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookclub_id'], ['bookclubs.id'], name=op.f('fk_chatlogs_bookclub_id_bookclubs')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookclub_books',
    sa.Column('bookclub_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_bookclub_books_book_id_books')),
    sa.ForeignKeyConstraint(['bookclub_id'], ['bookclubs.id'], name=op.f('fk_bookclub_books_bookclub_id_bookclubs')),
    sa.PrimaryKeyConstraint('bookclub_id', 'book_id')
    )
    op.create_table('bookshelf_books',
    sa.Column('bookshelf_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_bookshelf_books_book_id_books')),
    sa.ForeignKeyConstraint(['bookshelf_id'], ['bookshelves.id'], name=op.f('fk_bookshelf_books_bookshelf_id_bookshelves')),
    sa.PrimaryKeyConstraint('bookshelf_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookshelf_books')
    op.drop_table('bookclub_books')
    op.drop_table('chatlogs')
    op.drop_table('bookshelves')
    op.drop_table('books')
    op.drop_table('bookclub_users')
    op.drop_table('users')
    op.drop_table('bookclubs')
    # ### end Alembic commands ###
