"""book model update

Revision ID: d58a85e25a1a
Revises: 998e6ac4b0d4
Create Date: 2025-02-08 15:36:57.852778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58a85e25a1a'
down_revision = '998e6ac4b0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('spine_image', sa.String(), nullable=True))
        batch_op.drop_column('spin_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spin_image', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('spine_image')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
